forename = input("what is your forename")
lastname = input ("what is your lastname")
address = input ("what is your address")
age = input ("what is you age")
hieght=input("what is your hieght")
print("hello",forename,lastname)
print ("who lives in",address)
print("who's hieght is",hieght)
print("who is",age)
